apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: eks-cluster-secrets
  namespace: kube-system
spec:
  backendType: secretsManager
  roleArn: arn:aws:iam::042110863587:role/FlybitsInfra-infra-eks-controlplane-EksClusterRole-10060ZCXBHMSR
  dataFrom:
    - infra-eks-cluster
