apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filebeat
  namespace: kube-system
spec:
  template:
    spec:
      containers:
      - name: filebeat
        resources:
          requests:
            cpu: 0.01
            memory: "100Mi"
          limits:
            cpu: 0.5
            memory: "500Mi"