apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: default
spec:
  template:
    spec:
      requirements:
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - spot
        - on-demand
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      - key: karpenter.k8s.aws/instance-category
        operator: In
        values:
        - c
        - m
        - r
        - t
      - key: karpenter.k8s.aws/instance-family
        operator: NotIn
        values: ["c7i-flex"]
      - key: karpenter.k8s.aws/instance-size
        operator: NotIn
        values:
        - nano
        - micro
      - key: karpenter.k8s.aws/instance-generation
        operator: Gt
        values:
        - "4"
      startupTaints:
      - effect: NoExecute
        key: node.cilium.io/agent-not-ready
        value: "true"
---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiSelectorTerms:
  - name: "amazon-eks-node-1.31-v20250103"
    owner: amazon
  # Propagates tags to underlying EC2 resources
  # cost-reduction-pipeline tag is used in Cost Reduction Pipeline
  tags:
    cost-reduction-pipeline: $(CONFIG_EKS_CLUSTER)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: karpenter
  namespace: kube-system
spec:
  template:
    spec:
      nodeSelector:
        AppType: "karpenter"
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - key: "AppType"
        operator: "Equal"
        value: "karpenter"
        effect: "NoExecute"