apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-operator
  namespace: mongodb
data:
  projectName: "infra"
---
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: flybits
  namespace: mongodb
spec:
  version: 7.0.15-ent
  featureCompatibilityVersion: "7.0"