kind: Secret
apiVersion: v1
metadata:
  name: mongodb-backup-secrets
  namespace: default
type: Opaque
stringData:
  password: <path:$(PATH_ARN):$(ENVIRONMENT_ID)#MONGODB_BACKUP_PASSWORD>
  user: <path:$(PATH_ARN):$(ENVIRONMENT_ID)#MONGODB_BACKUP_USERNAME>
  host: <path:$(PATH_ARN):$(ENVIRONMENT_ID)#MONGODB_BACKUP_HOST>
  bucket: <path:$(PATH_ARN):$(ENVIRONMENT_ID)#MONGODB_BACKUP_S3_BUCKET>
  bucket_to_fail: <path:$(PATH_ARN):$(ENVIRONMENT_ID)#MONGODB_BACKUP_S3_BUCKET_TO_FAIL>
