apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# - infra-namespace
# # - ../../base/linkerd
# - ../../base/filebeat-opensearch
# - ../../base/logrotate
# - ../../base/kube-system
# # - ../../base/kube-system/nodelocal-dns
# - ../../base/kube-system/local-dns
# # - external-dns.yaml
# # - dns-horizontal-autoscaler.yaml
# - ../../base/mongodb-operator-enterprise/
# # - ../../base/observability/base
# #- ../../base/observability/metricbeat
# # - cluster-autoscaler-priority-expander-cm.yaml
#  - ../../../../base/rabbitmq_2.15.1
# - ../../base/secrets
# # - ../../base/secrets/observability
# - ../../base/secrets/mongodb
# - ../../base/envoyproxy-ratelimit
- ../../../../base/cert-manager
# - ../../base/karpenter
# - ../../base/kube-prometheus
# - ../../base/grafana/agent
# - ../../base/gatekeeper
# - mongodb-backup-secret.yaml
# - mongodb-backup-job.yaml

commonAnnotations:
  "flybits.environment": infra

#patchesStrategicMerge:
# - mongodb-clusters.yaml
# - filebeat/config.yaml
# - nodeSelector-patch.yaml
#  - rabbitmq.yaml
# - karpenter-nodepool.yaml
# # - nodelocaldns-patches.yaml
# - filebeat-patch.yaml
# - kube-prometheus/prometheus-server.yaml
# - kube-prometheus/prometheus-alertmanager.yaml
# - gatekeeper-patch.yaml
# - envoyproxy-ratelimit-patch.yaml

#patches:
  # - target:
  #     kind: Deployment
  #     name: external-dns
  #   patch: |
  #     - op: add
  #       path: /spec/template/spec/containers/0/args/0
  #       value: --domain-filter=flybits-infra-042110863587.net
  # - target:
  #     kind: AlertmanagerConfig
  #     name: config-alertmanager
  #     namespace: default
  #   patch: |
  #     - op: remove
  #       path: /spec/receivers/3
  #       value:
  #         name: 'opsgenie-ticketing'
  #     - op: remove
  #       path: /spec/route/routes/3
  #       value:
  #         receiver: 'opsgenie-ticketing'
  # No need for a PDB for prometheus-k8s since it has only one replica in infra
  # - patch: |-
  #     apiVersion: policy/v1
  #     kind: PodDisruptionBudget
  #     metadata:
  #       name: prometheus-k8s
  #     $patch: delete
  #   target:
  #       group: policy
  #       version: v1
  #       kind: PodDisruptionBudget
  #       name: prometheus-k8s

# configMapGenerator:
# - name: system-config
#   namespace: kube-system
#   behavior: merge
#   literals:
#   - eks-cluster=infra-eks-cluster
#   - aws-region=us-east-1
#   - dns-domain-filter=infra.flybits.com
#   - dns-owner-id=Z0234500G32Y6J0QSUGV
#   - aws-account-id=042110863587
#   - environment=infra
# - name: secrets-config
#   namespace: $(ENVIRONMENT_NAME_SECRET)
#   behavior: merge
#   literals:
#   - environment-id=infra-2ty8HU
# - name: prometheus-config
#   namespace: monitoring
#   behavior: merge
#   literals:
#     - prometheus-environment=infra
#     - environment_tier="lower"
#     - group_interval="1h"
#     - group_wait="10s"
#     - repeat_interval="12h"
#     - slack_webhook_channel="#alerts-lower-envs"
#     - requests_slack_webhook_channel="#alerts-latency-lower-envs"
#     - latency_slack_webhook_channel="#alerts-request-errors-lower-envs"
#     - rabbitmq_queue_messages_threshold="200000"
#     - rabbitmq_total_messages_threshold="1000000"
#     - rabbitmq_connections_threshold="1000"
# - name: grafana-config
#   namespace: monitoring
#   behavior: merge
#   literals:
#     - grafana_url="https://logs-prod-006.grafana.net"

# configurations:
#   - transformer_config.yaml