# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: cert-manager-cainjector
#   namespace: cert-manager
# spec:
#   template:
#     spec:
#       nodeSelector:
#         AppType: "essentials"
#       tolerations:
#       - key: "AppType"
#         operator: "Equal"
#         value: "essentials"
#         effect: "NoExecute"
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: cert-manager
#   namespace: cert-manager
# spec:
#   template:
#     spec:
#       nodeSelector:
#         AppType: "essentials"
#       tolerations:
#       - key: "AppType"
#         operator: "Equal"
#         value: "essentials"
#         effect: "NoExecute"
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: cert-manager-webhook
#   namespace: cert-manager
# spec:
#   template:
#     spec:
#       nodeSelector:
#         AppType: "essentials"
#       tolerations:
#       - key: "AppType"
#         operator: "Equal"
#         value: "essentials"
#         effect: "NoExecute"
---
# Just to avoid SharedResourceWarning on ArgoCD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    app.kubernetes.io/instance: null
  name: certificaterequests.cert-manager.io
---
# Just to avoid SharedResourceWarning on ArgoCD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    app.kubernetes.io/instance: null
  name: certificates.cert-manager.io
---
# Just to avoid SharedResourceWarning on ArgoCD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    app.kubernetes.io/instance: null
  name: challenges.acme.cert-manager.io
---
# Just to avoid SharedResourceWarning on ArgoCD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    app.kubernetes.io/instance: null
  name: clusterissuers.cert-manager.io
---
# Just to avoid SharedResourceWarning on ArgoCD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    app.kubernetes.io/instance: null
  name: issuers.cert-manager.io
---
# Just to avoid SharedResourceWarning on ArgoCD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    app.kubernetes.io/instance: null
  name: orders.acme.cert-manager.io