kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: run-efs-provisioner
subjects:
  - kind: ServiceAccount
    name: efs-provisioner
    namespace: infra


---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: leader-locking-efs-provisioner
subjects:
  - kind: ServiceAccount
    name: efs-provisioner
    namespace: infra


---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: efs-provisioner
spec:
  template:
    spec:
      volumes:
        - name: pv-volume
          nfs:
            server: fs-04122d87.efs.us-east-1.amazonaws.com
            path: /
