apiVersion: apps/v1
kind: Deployment
metadata:
  name: speedtest
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: speedtest
  template:
    metadata:
      labels:
        app: speedtest
    spec:
      containers:
      - image: adolfintel/speedtest
        name: speedtest
        ports:
        - containerPort: 80
