apiVersion: v1
kind: LimitRange
metadata:
  name: default-mem-cpu-limit
spec:
  limits:
  - default:
      memory: 200Mi
      cpu: 0.5
    defaultRequest:
      memory: 200Mi
      cpu: 0.01
    type: Container
