apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo
  namespace: argocd
spec:
  project: default
  destination:
    namespace: kargo
    server: https://kubernetes.default.svc
  sources:
    - repoURL: ghcr.io/akuity/kargo-charts
      chart: kargo
      targetRevision: "1.7.4"
      helm:
        valueFiles:
          - $values/kargo/values.yaml
    - repoURL: https://github.com/derekneves/argocd
      targetRevision: main
      ref: values
      path: kargo/values.yaml
  syncPolicy:
    syncOptions:
    - CreateNamespace=true